# Generated by Django 6.0.7 on 2026-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parkingzone',
            constraint=models.UniqueConstraint(fields=('parking', 'name'), name='unique_zone_name_per_parking'),
        ),
    ]
