# Generated by Django 6.0.6 on 2026-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_created_at_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
