# Generated by Django 6.0.7 on 2026-07-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom_deposeur', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('heure_entree', models.DateTimeField()),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PARKED', 'Garé'), ('EXITED', 'Sorti'), ('CANCELLED', 'Annulé')], default='PARKED', max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='vehicles.vehicle')),
            ],
        ),
    ]
