# Generated by Django 6.0.7 on 2026-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('PARKED', 'Gare'), ('EXITED', 'Sorti'), ('CANCELLED', 'Annule')], default='PARKED', max_length=20),
        ),
    ]
