# Generated by Django 6.0.6 on 2026-07-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_code_alter_location_statut'),
        ('parkings', '0002_parkingzone_unique_zone_name_per_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parking_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='parkings.parkingzone'),
        ),
    ]
