# Generated by Django 6.0.7 on 2026-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_parking_zone'),
        ('parkings', '0003_remove_parking_model'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['statut'], name='location_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['vehicle', 'statut'], name='location_vehicle_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['parking_zone', 'statut'], name='location_zone_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['heure_entree'], name='location_entree_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['heure_sortie'], name='location_sortie_idx'),
        ),
    ]
