# Generated by Django 6.0.7 on 2026-07-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('ORANGE_MONEY', 'Orange Money'), ('MPESA', 'M-Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('ILLICOCASH', 'Illicocash')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='locations.location')),
            ],
        ),
    ]
